class CatalogConstants:
    PRODUCT_MENU_ELECTRIC_SCOOTERS_XPATH = ".//a[@href='/ehlektrosamokaty/'][@data-target='menu-tab-1055']"
    PRODUCT_MENU_GIROBORDS_XPATH = ".//a[@href='/girobordy/'][@data-target='menu-tab-1057']"
    PRODUCT_MENU_GIROSCUTERS_XPATH = ".//a[@href='/giroskutery/'][@data-target='menu-tab-1058']"
    PRODUCT_MENU_SPAREPARTS_XPATH = ".//a[@href='/zapchasti/'][@data-target='menu-tab-1059']"
    PRODUCT_MENU_SPECIALS_XPATH = ".//a[@href='/specials/'][@data-target='menu-tab-1083']"
    CATALOG_FIRST_ITEM_XPATH = ".//ul[@class='catalogGrid catalog-grid catalog-grid--m catalog-grid--sidebar']/li[@class='catalog-grid__item']"
    CATALOG_FORM_WISH_LIST_ITEMS_XPATH = ".//ul[@class='catalogGrid catalog-grid catalog-grid--m catalog-grid--sidebar']"
    CATALOG_BUY_BUTTON_XPATH = ".//a[@class='btn __special j-buy-button-add']"
    CATALOG_CART_ITEM_QUANTITY_XPATH = ".//input[@class='counter-field j-quantity-p']"
    CATALOG_SET_ORDER_BUTTON_XPATH = ".//a[@href='/checkout/']"
    CATALOG_ORDER_FORM_SET_REGISTERED_USER_XPATH = ".//a[@href='#checkout-login']"
    CATALOG_ORDER_FORM_SET_NEW_USER_XPATH = ".//a[@href='#checkout-signup']"
    CATALOG_ORDER_FORM_QUIK_ORDER_XPATH = ".//a[@href='#checkout-quick']"
    CATALOG_ORDER_FORM_LOGIN_XPATH_XPATH = ".//input[@type='submit'][@value='Увійти']"
    CATALOG_ORDER_FORM_ENABLED_ORDER_BUTTON_XPATH = ".//span[@class='btn j-submit __special']"
    CATALOG_ORDER_FORM_USER_PHONE_XPATH = ".//input[@name='Recipient[delivery_phone]']"
    CATALOG_ORDER_FORM_USER_TOWN_FIELD_XPATH = ".//input[@name='Recipient[delivery_city]']"
    CATALOG_ORDER_FORM_TOWN_LIST_XPATH = ".//li[@class='ui-menu-item'][text()="
    CATALOG_ORDER_FORM_NEW_USER_XPATH = ".//input[@name='Recipient[delivery_name]']"
    CATALOG_ORDER_FORM_NEW_USER_EMAIL_XPATH = ".//input[@name='Recipient[delivery_email]']"
    CATALOG_ORDER_FORM_DELIVERY_ADDRESS_XPATH = ".//input[@name='Delivery[delivery_method][delivery_address]']"
    CATALOG_ORDER_FORM_DELIVERY_TYPE_XPATH = ".//span[@name='Delivery[delivery_type]']"
    CATALOG_ORDER_FORM_QUICK_USER_XPATH = ".//input[@name='Quick[delivery_name]']"
    CATALOG_ORDER_FORM_QUICK_USER_EMAIL_XPATH = ".//input[@name='Quick[delivery_email]']"
    CATALOG_ORDER_FORM_QUICK_USER_PHONE_XPATH = ".//input[@name='Quick[delivery_phone]']"
    CATALOG_ORDER_FORM_QUICK_ORDER_BUTTON_XPATH = ".//input[@class='btn-input'][@value='Оформити замовлення']"
    CATALOG_ORDER_FORM_QUIK_ORDER_FORM_BUTTON_XPATH = ".//span[@class='btn-content'][text()='Замовити швидко']"
    CATALOG_QUICK_ORDER_FORM_USERNAME_XPATH = ".//input[@name='ProductQuick[delivery_name]']"
    CATALOG_QUICK_ORDER_FORM_EMAIL_XPATH = ".//input[@name='ProductQuick[delivery_email]']"
    CATALOG_QUICK_ORDER_FORM_PHONE_XPATH = ".//input[@name='ProductQuick[delivery_phone]']"
    ELECTRIC_SCOOTER_BRAND_CROSSER_XPATH = ".//a[@class='children-pages-menu__link'][@href='/ehlektrosamokaty/ehlektrosamokaty-crosser/']"
    ELECTRIC_SCOOTER_BRAND_SEGWAY_XPATH = ".//a[@class='children-pages-menu__link'][@href='/ehlektrosamokaty/segway/']"
    ELECTRIC_SCOOTER_BRAND_CITY_RIDER_XPATH = ".//a[@class='children-pages-menu__link'][@href='/ehlektrosamokaty/city-rider/']"
    ELECTRIC_SCOOTER_BRAND_BESTSCOOTER_XPATH = ".//a[@class='children-pages-menu__link'][@href='/ehlektrosamokaty/bestscooter/']"
    ELECTRIC_SCOOTER_BRAND_KUGO_XPATH = ".//a[@class='children-pages-menu__link'][@href='/ehlektrosamokaty/ehlektrosamokaty-kugoo/']"
    ELECTRIC_SCOOTER_BRAND_SNS_XPATH = ".//a[@class='children-pages-menu__link'][@href='/ehlektrosamokaty/ehlektrosamokaty-sns']"
    ELECTRIC_SCOOTER_BRAND_XIAOMI_XPATH = ".//a[@class='children-pages-menu__link'][@href='/ehlektrosamokaty/ehlektrosamokaty-xiaomi/']"
    ELECTRIC_SCOOTER_BRAND_JOYOR_XPATH = ".//a[@class='children-pages-menu__link'][@href='/ehlektrosamokaty/ehlektrosamokaty-joyor/']"
    ELECTRIC_SCOOTER_BRAND_SMALL_CHILD_XPATH = ".//a[@class='children-pages-menu__link'][@href='/ehlektrosamokaty/detskie-ehlektrosamokaty/']"
    GIROBORDS_TYPES_65_INCH_XPATH = ".//a[@class='children-pages-menu__link'][@href='/girobordy/girobordy-65-dyujmov/']"
    GIROBORDS_TYPES_8_INCH_XPATH = ".//a[@class='children-pages-menu__link'][@href='/girobordy/girobordy-8-dyujmov/']"
    ELEMENT_HAS_BLOCK_BUY_XPATH = ".//div[@class='product-order__block product-order__block--buy']"
    CATALOG_CART_REMOVE_CSS_PATH = "svg.icon.icon--cart-remove"
    CATALOG_CART_QUANTITY_XPATH = ".//div[@class='basket__items']"
    CATALOG_FORM_WISH_BUTTON_XPATH = ".//span[@class='favorites-button__icon favorites-button__icon--s']"
